common/models/Witel.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "witel".
 *
 * @property string $id
 * @property string|null $nama
 *
 * @property Datel[] $datels
 */
class Witel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'witel';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'string', 'max' => 2],
            [['nama'], 'string', 'max' => 128],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * Gets query for [[Datels]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUbiskecamatan()
    {
        return $this->hasMany(UbisKecamatan::className(), ['ubis_id' => 'id'])
                    ->via('Ubiss');
    }

    public function getUsers()
    {
        return $this->hasMany(User::className(), ['ubis_id' => 'id'])
                    ->via('Ubiss');
    }

    public function getUbiss()
    {
        return $this->hasMany(Ubis::className(), ['datel_id' => 'id'])
                    ->via('Datels');
    }

    public function getDatels()
    {
        return $this->hasMany(Datel::className(), ['witel_id' => 'id']);
    }


}

backend/controllers/WitelController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Pelanggan;
use common\models\PelangganSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\KotaKabupaten;
use common\models\Kecamatan;
use common\models\KecamatanSearch;
use common\models\DesaKelurahan;
use common\models\UbisKecamatan;
use common\models\UbisKecamatanSearch;
use backend\models\User;
use backend\models\UserSearch;
use yii\web\UploadedFile;
use yii\rbac\ManagerInterface;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use dektrium\user\traits\EventTrait;
use dektrium\user\Finder;


/**
 * PelangganController implements the CRUD actions for Pelanggan model.
 */
class WitelController extends Controller
{
    public $uploadParam = 'file';

    use EventTrait;

    const EVENT_BEFORE_CREATE = 'beforeCreate';
    const EVENT_AFTER_CREATE = 'afterCreate';
    const EVENT_BEFORE_UPDATE = 'beforeUpdate';
    const EVENT_AFTER_UPDATE = 'afterUpdate';

    /** @var Finder */
    protected $finder;

    /**
     * @param string  $id
     * @param Module2 $module
     * @param Finder  $finder
     * @param array   $config
     */
    public function __construct($id, $module, Finder $finder, $config = [])
    {
        $this->finder = $finder;
        parent::__construct($id, $module, $config);
    }
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionHome()
    {
        return $this->render('home');
    }

    public function actionDashboard($id)
    {
        $searchModel = new PelangganSearch();  
        
        $subQuery = User::find()->select('id')->where(['ubis_id'=> Yii::$app->user->identity->ubis_id])
        ->andWhere(['>','id',200]);
        
        switch ($id) {
            case 1:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery]);
              break;
            case 2:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery,'status_id'=>101]);
              break;
            case 3:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery,'hasil_id'=>201]);
              break;
            case 4:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery,'hasil_id'=>203]);
              break;
           
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);


    }

    /**
     * Lists all Pelanggan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Pelanggan();
        $searchModel = new PelangganSearch();

        $role = Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId());
        $ubis_id = Yii::$app->user->identity->ubis_id;

        $subQuery = UbisKecamatan::find()->select('kecamatan_id')
                                    ->joinWith('ubis.datel')
                                    ->where(['witel_id'=>$ubis_id]);

        $query = Pelanggan::find()->where(['kecamatan_id'=> $subQuery]);

        if ($model->load(Yii::$app->request->post())) {
            $start =  $model->start_date;
            $end =  $model->end_date;

            $query = Pelanggan::find()->where(['kecamatan_id'=> $subQuery])
                                      ->andWhere(['>=','tanggal_submit',strtotime($start)])
                                      ->andWhere(['<=','tanggal_submit',strtotime($end)]);

        }
        
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
          
        ]);
    }

    public function actionTambahsf()
    {
        /** @var User $user */
        $user = \Yii::createObject([
            'class'    => User::className(),
            'scenario' => 'create',
        ]);
        $event = $this->getUserEvent($user);

        $this->performAjaxValidation($user);

        $this->trigger(self::EVENT_BEFORE_CREATE, $event);
        if ($user->load(\Yii::$app->request->post()) && $user->create()) {
            \Yii::$app->getSession()->setFlash('success', \Yii::t('user', 'User has been created'));
            $this->trigger(self::EVENT_AFTER_CREATE, $event);
            return $this->redirect(['update', 'id' => $user->id]);
        }

        return $this->render('tambahsf', [
            'user' => $user,
        ]);
    }

    public function actionUpdatesf($id)
    {
        Url::remember('', 'actions-redirect');
        $user = $this->findModels($id);
        $user->scenario = 'update';
        $event = $this->getUserEvent($user);

        $this->performAjaxValidation($user);

        $this->trigger(self::EVENT_BEFORE_UPDATE, $event);
        if ($user->load(\Yii::$app->request->post()) && $user->save()) {
            \Yii::$app->getSession()->setFlash('success', \Yii::t('user', 'Account details have been updated'));
            $this->trigger(self::EVENT_AFTER_UPDATE, $event);
            return $this->refresh();
        }

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    public function actionApprove($id)
    {
        $user = User::findOne($id);
        $user->status = 1;
        $user->save();

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    public function actionRefuse($id)
    {
        $user = User::findOne($id);
        $user->status = 98;
        $user->save();

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    public function actionDaftarsf()
    {
        $searchModel = new UserSearch();

        // $query = User::find()->where(['ubis_id'=>Yii::$app->user->identity->ubis_id])
        //                      ->andWhere(['>','id',1000]);
        $query = User::find()->joinWith('witel')->where(['user.witel_id'=>Yii::$app->user->identity->witel_id])
                             ->andWhere(['>','user.id',499])
                             ->orderBy(['status' => SORT_DESC]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('daftarsf', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWilayah()
    {
        $ubis_id = Yii::$app->User->identity->ubis_id;
        $subquery = UbisKecamatan::find()->joinWith('witel')->select('kecamatan_id')->where(['witel.id'=>$ubis_id]);  
        $query = DesaKelurahan::find()->joinWith('kecamatan')->where(['kecamatan.id'=>$subquery]);
          
        $searchModel = new KecamatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('wilayah', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pelanggan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Pelanggan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pelanggan();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionCreate2()
    {
        $model = new Pelanggan();

        if ($model->load(Yii::$app->request->post())) {
            $model->salesforce_id = 3;
            $model->save();

            return $this->render('hello');
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pelanggan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pelanggan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pelanggan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pelanggan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {

backend/views/witel/_account.php
<?php

/*
 * This file is part of the Dektrium project
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var dektrium\user\models\User $user
 */
?>

<?php $this->beginContent('@backend/views/witel/updatesf.php', ['user' => $user]) ?>

<?php $form = ActiveForm::begin([
    'layout' => 'horizontal',
    'enableAjaxValidation' => true,
    'enableClientValidation' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'wrapper' => 'col-sm-9',
        ],
    ],
]); ?>

<?= $this->render('_user', ['form' => $form, 'user' => $user]) ?>

<div class="form-group">
    <div class="col-lg-offset-3 col-lg-9">
        <?= Html::submitButton(Yii::t('user', 'Update'), ['class' => 'btn btn-block btn-success']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

<?php $this->endContent() ?>

backend/views/witel/_user.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

/**
 * @var yii\widgets\ActiveForm $form
 * @var dektrium\user\models\User $user
 */
use common\models\Ubis;
use yii\helpers\ArrayHelper;

$ubis = ArrayHelper::map(Ubis::find()->asArray()->all(), 'id', 'nama');

?>

<?= $form->field($user, 'nik')->textInput(['maxlength' => 255]) ?>
<?= $form->field($user, 'nama')->textInput(['maxlength' => 255]) ?>
<?= $form->field($user, 'no_handphone')->textInput(['maxlength' => 255]) ?>
<?= $form->field($user, 'email')->textInput(['maxlength' => 255]) ?>
<?= $form->field($user, 'ubis_id')->dropDownList($ubis) ?>

backend/views/witel/daftarsf.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Witel;
use common\models\Ubis;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Button;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Daftar Sales Force';
$this->params['breadcrumbs'][] = $this->title;

$ubis_id = Yii::$app->user->identity->ubis_id;
$witel = Witel::find()->where(['id'=>$ubis_id])->one();
// $ubis = Ubis::find()->where(['id'=>$ubis_id])->one()->nama;

$check = ArrayHelper::map(Ubis::listUbis(Yii::$app->user->identity->witel_id), 'id', 'nama');
$array = [0 => 'NOT SET'];
$ubis = $check+$array;


?>
<div class="user-index box box-primary">
    <div class="box-header with-border">
    <div class="pull-left">
    <?=  Button::widget([
        'label' => 'WITEL : '. $witel->nama,
        'options' => ['class' => 'btn btn-success']]);?>
    </div>
    <!-- <div class="pull-right">
        <?= Html::a('Tambah SF', ['tambahsf'], ['class' => 'btn btn-primary']) ?>
    </div> -->
    
    
    </div>



    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                // [
                //     'label' => 'Nama Witel',
                //     'attribute' => 'witel',
                //     'filter' => ArrayHelper::map(Witel::find()->asArray()->all(), 'id', 'nama'),
                //     'value'=> 'witel.nama', //relation name with their attribute
                // ],
                [
                    'label' => 'Nama UBIS',
                    'attribute' => 'ubis',
                    'filter' => $ubis, //ArrayHelper::map(Ubis::listUbis(Yii::$app->user->identity->witel_id), 'id', 'nama'),
                    'value'=> 'ubis.nama', //relation name with their attribute
                ], 
                // [
                //     'label' => 'Kode UBIS',
                //     'attribute' => 'ubis_id',
                //     'value'=> 'ubis.kode_ubis', //relation name with their attribute
                // ],
                'nik',
                'nama',
				'no_handphone',
                'email:email',
                // 'order',                 
                // 'password_hash',
                // 'auth_key',
                // 'confirmed_at',
                // 'unconfirmed_email:email',
                // 'blocked_at',
                // 'registration_ip',
                // 'created_at',
                // 'updated_at',
                // 'last_login_at',
                // 'avatar',
                [
                    'label' => 'Lenght of Stay',
                    'attribute' => 'active_at',
                    'format'=> 'raw',
                    'filter' => array('0' =>'>6 BULAN','1'=>'>1 TAHUN'),
                    'value' => function ($model) {
                        return Yii::$app->formatter->format($model->active_at, 'relativeTime');
                    }
                ],
                [
                    'label' => 'Status',
                    'attribute' => 'status',
                    'format' => 'raw',
                    'filter' => array('0' =>'INACTIVE','1'=>'ACTIVE','99'=>'NEED APPROVAL','98'=>'REFUSED'),
                    'value'=> function ($model) {
                        if($model->status == 1) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-success btn-block',
                                ]);
                        } elseif ($model->status == 0) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-danger btn-block',
                                ]);
                        } elseif ($model->status == 99) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-primary btn-block',
                                ]);
                        }
                        elseif ($model->status == 98) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-warning btn-block',
                                ]);
                        }
                      }, 
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{updatesf}',
                    'buttons' => [
                        'updatesf' => function ($url,$model,$key) {
                                return Html::a('<span class="glyphicon glyphicon-edit"></span>', $url, ['class'=>'btn btn-xs btn-warning']);
                        },
                    ],
                ],

            ],
        ]); ?>
    </div>
</div>

backend/views/witel/home.php
<?php

/* @var $this yii\web\View */

use common\models\Pelanggan;
use common\models\User;
use yii\helpers\Html;

$this->title = 'Dashboard';

$subQuery = User::find()->select('id')->where(['ubis_id'=> Yii::$app->user->identity->ubis_id])
->andWhere(['>','id',200]);

?>
      <!-- Small boxes (Stat box) -->
<div class="row">
<div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery])
                                ->count();              
        ?>
        </h3>
        <h4>Jumlah Hit</h4>
      </div>
      <div class="icon">
        <i class="fa fa-chevron-circle-up"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>1], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-yellow">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery,
                                         'status_id'=>101])->count();              
        ?>              
        </h3>
        <h4>Belum Lapor Follow Up</h4>
      </div>
      <div class="icon">
        <i class="fa fa-question-circle"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>2], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-orange">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery,
                                         'hasil_id'=>201])->count();
                           
        ?>    
        </h3>
        <h4>Belum Lapor Hasil</h4>
      </div>
      <div class="icon">
        <i class="fa fa-question-circle"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>3], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>
    </div>
  </div>

  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery,
                                         'hasil_id'=>203])->count();                
        ?>    
        </h3>
        <h4>Belum Deal</h4>
      </div>
      <div class="icon">
        <i class="fa fa-times-circle"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>4], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>    </div>
  </div>
  <!-- ./col -->
</div>

      

backend/views/witel/tambahsf.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Nav;
use yii\helpers\Html;
use yii\bootstrap\Alert;

/**
 * @var yii\web\View $this
 * @var dektrium\user\models\User $user
 */

use common\models\Ubis;
use yii\helpers\ArrayHelper;

$ubis = ArrayHelper::map(Ubis::find()->asArray()->all(), 'id', 'nama');

$this->title = Yii::t('user', 'Tambah Salesforce');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['witel/index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pelanggan-index box box-primary">
    <div class="box-header with-border">

<?php 
    $module = Yii::$app->getModule('user');
    if ($module->enableFlashMessages): ?>
    <div class="row">
        <div class="col-xs-12">
            <?php foreach (Yii::$app->session->getAllFlashes() as $type => $message): ?>
                <?php if (in_array($type, ['success', 'danger', 'warning', 'info'])): ?>
                    <?= Alert::widget([
                        'options' => ['class' => 'alert-dismissible alert-' . $type],
                        'body' => $message
                    ]) ?>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>



<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <?= Nav::widget([
                    'options' => [
                        'class' => 'nav-pills nav-stacked',
                    ],
                    'items' => [
                        ['label' => 'Daftar Salesforce', 'url' => ['/witel/sflist']],
                    ],
                ]) ?>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="alert alert-info">
                    <?= Yii::t('user', 'Credentials will be sent to the user by email') ?>.
                    <?= Yii::t('user', 'A password will be generated automatically if not provided') ?>.
                </div>
                <?php $form = ActiveForm::begin([
                    'layout' => 'horizontal',
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => false,
                    'fieldConfig' => [
                        'horizontalCssClasses' => [
                            'wrapper' => 'col-sm-9',
                        ],
                    ],
                ]); ?>
                <?= $form->field($user, 'nik')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($user, 'no_handphone')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($user, 'email')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($user, 'ubis_id')->dropDownList($ubis, [
                    'prompt'=>'PILIH UBIS',
                 ]) ?>
                <?= $form->field($user, 'password')->passwordInput() ?>
               

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-9">
                        <?= Html::submitButton(Yii::t('user', 'Save'), ['class' => 'btn btn-block btn-success']) ?>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>
</div>
</div>

backend/views/witel/updatesf.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\Nav;
use yii\bootstrap\Alert;
use yii\helpers\Html;


/**
 * @var \yii\web\View $this
 * @var \dektrium\user\models\User $user
 * @var string $content
 */

$this->title = Yii::t('user', 'Perbarui Data Salesforce');


?>
<div class="pelanggan-index box box-primary">
    <div class="box-header with-border">

    


<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
        <div class="box-body box-profile">
            <?= Html::img('@web/uploads/avatar/'.$user->avatar, 
                ['alt' => 'avatar','class'=>'profile-user-img img-responsive',
                'style'=> 'width:400px']) 
            ?>

            <h3 class="profile-username text-center"><?= $user->nama ?></h3>
            
            <p class="text-muted text-center"></p>

            </div>
            <div class="panel-body">
            <?= Nav::widget([
                    'options' => [
                        'class' => 'nav-pills nav-stacked',
                    ],
                    'items' => [
        
                        [
                            'label' => Yii::t('user', 'Approve'),
                            'url' => ['/witel/approve', 'id' => $user->id],
                            'visible' => $user->isNeedApprove,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Refuse'),
                            'url' => ['/witel/refuse', 'id' => $user->id],
                            'visible' => $user->isNeedApprove,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Confirm'),
                            'url' => ['/user/admin/confirm', 'id' => $user->id],
                            'visible' => !$user->isConfirmed,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Block'),
                            'url' => ['/user/admin/block', 'id' => $user->id],
                            'visible' => !$user->isBlocked,
                            'linkOptions' => [
                                'class' => 'text-danger',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to block this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Unblock'),
                            'url' => ['/user/admin/block', 'id' => $user->id],
                            'visible' => $user->isBlocked,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to unblock this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Delete'),
                            'url' => ['/user/admin/delete', 'id' => $user->id],
                            'linkOptions' => [
                                'class' => 'text-danger',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to delete this user?'),
                            ],
                        ],
                    ],
                ]) ?>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <?= $content ?>
            </div>
        </div>
    </div>
</div>
</div>
</div>