common/models/Ubis.php
<?php

namespace common\models;
use backend\models\User;

use Yii;

/**
 * This is the model class for table "ubis".
 *
 * @property string $id
 * @property string|null $datel_id
 * @property string|null $kode_ubis
 * @property string|null $nama
 *
 * @property Datel $datel
 * @property ubisKecamatan[] $ubisKecamatans
 * @property Kecamatan[] $kecamatans
 */
class Ubis extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ubis';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'string', 'max' => 6],
            [['datel_id'], 'string', 'max' => 4],
            [['kode_ubis'], 'string', 'max' => 128],
            [['nama'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['datel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Datel::className(), 'targetAttribute' => ['datel_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'datel_id' => 'Datel ID',
            'kode_ubis' => 'Kode Ubis',
            'nama' => 'Nama',
        ];
    }

    /**
     * Gets query for [[Datel]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getWitel()
    {
        return $this->hasOne(Datel::className(), ['id' => 'witel_id'])
        ->via('datel');
    }
    
     public function getDatel()
    {
        return $this->hasOne(Datel::className(), ['id' => 'datel_id']);
    }

    /**
     * Gets query for [[UbisKecamatans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUbisKecamatans()
    {
        return $this->hasMany(UbisKecamatan::className(), ['ubis_id' => 'id']);
    }

    /**
     * Gets query for [[Kecamatans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKecamatans()
    {
        return $this->hasMany(Kecamatan::className(), ['id' => 'kecamatan_id'])->viaTable('ubis_kecamatan', ['ubis_id' => 'id']);
    }

    public function getUser()
    {
        return $this->hasMany(User::className(), ['ubis_id' => 'id']);
    }

    public function listUbis($witel)
    {
        $ubis = Ubis::find()->asArray()->joinWith('datel')->where(['witel_id' => $witel])
                                                        ->orderBy('id ASC')
                                                        ->all();
                                       
        return $ubis;
    }
}

backend/controllers/UbisController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Pelanggan;
use common\models\PelangganSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\KotaKabupaten;
use common\models\Kecamatan;
use common\models\KecamatanSearch;
use common\models\DesaKelurahan;
use common\models\UbisKecamatan;
use common\models\UbisKecamatanSearch;
use backend\models\User;
use backend\models\UserSearch;
use yii\web\UploadedFile;
use yii\rbac\ManagerInterface;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use dektrium\user\traits\EventTrait;
use dektrium\user\Finder;


/**
 * PelangganController implements the CRUD actions for Pelanggan model.
 */
class UbisController extends Controller
{
    public $uploadParam = 'file';

    use EventTrait;

    const EVENT_BEFORE_CREATE = 'beforeCreate';
    const EVENT_AFTER_CREATE = 'afterCreate';
    const EVENT_BEFORE_UPDATE = 'beforeUpdate';
    const EVENT_AFTER_UPDATE = 'afterUpdate';

    /** @var Finder */
    protected $finder;

    /**
     * @param string  $id
     * @param Module2 $module
     * @param Finder  $finder
     * @param array   $config
     */
    public function __construct($id, $module, Finder $finder, $config = [])
    {
        $this->finder = $finder;
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionHome()
    {
        return $this->render('home');
    }

    public function actionDashboard($id)
    {
        $searchModel = new PelangganSearch();  
        
        $subQuery = User::find()->select('id')->where(['ubis_id'=> Yii::$app->user->identity->ubis_id])
        ->andWhere(['>','id',200]);
        
        switch ($id) {
            case 1:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery]);
              break;
            case 2:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery,'status_id'=>101]);
              break;
            case 3:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery,'hasil_id'=>201]);
              break;
            case 4:
                $query = Pelanggan::find()->where(['salesforce_id'=> $subQuery,'hasil_id'=>203]);
              break;
           
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);


    }

    /**
     * Lists all Pelanggan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Pelanggan();
        $searchModel = new PelangganSearch();

        $role = Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId());
        $ubis_id = Yii::$app->user->identity->ubis_id;

        $subQuery = UbisKecamatan::find()->select('kecamatan_id')->where(['ubis_id' => $ubis_id]);
        $query = Pelanggan::find()->where(['kecamatan_id'=> $subQuery]);   
        
        if ($model->load(Yii::$app->request->post())) {
            $start =  $model->start_date;
            $end =  $model->end_date;

            $query = Pelanggan::find()->where(['kecamatan_id'=> $subQuery])
                                      ->andWhere(['>=','tanggal_submit',strtotime($start)])
                                      ->andWhere(['<=','tanggal_submit',strtotime($end)]);

        }
  
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
          
        ]);
    }

    public function actionUbiskec()
    {
        $query = UbisKecamatan::find();       
          
        $searchModel = new UbisKecamatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('ubiskec', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDaftarsf()
    {
        $searchModel = new UserSearch();

        $query = User::find()->where(['ubis_id'=>Yii::$app->user->identity->ubis_id])
                             ->andWhere(['>','id',500]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$query);

        return $this->render('daftarsf', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdatesf($id)
    {
        Url::remember('', 'actions-redirect');
        $user = $this->findModels($id);
        $user->scenario = 'update';
        $event = $this->getUserEvent($user);

        $this->performAjaxValidation($user);

        $this->trigger(self::EVENT_BEFORE_UPDATE, $event);
        if ($user->load(\Yii::$app->request->post()) && $user->save()) {
            \Yii::$app->getSession()->setFlash('success', \Yii::t('user', 'Account details have been updated'));
            $this->trigger(self::EVENT_AFTER_UPDATE, $event);
            return $this->refresh();
        }

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    public function actionApprove($id)
    {
        $user = User::findOne($id);
        $user->status = 1;
        $user->save();

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    public function actionRefuse($id)
    {
        $user = User::findOne($id);
        $user->status = 98;
        $user->save();

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    public function actionResetPassword($id)
    {
        $user = User::findOne($id);
        $user->password_hash = Yii::$app->security->generatePasswordHash('123456');
        $user->save();

        return $this->render('_account', [
            'user' => $user,
        ]);
    }

    

    /**
     * Displays a single Pelanggan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Pelanggan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pelanggan();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionCreate2()
    {
        $model = new Pelanggan();

        if ($model->load(Yii::$app->request->post())) {
            $model->salesforce_id = 3;
            $model->save();

            return $this->render('hello');
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pelanggan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pelanggan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pelanggan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pelanggan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pelanggan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findModels($id)
    {
        $user = $this->finder->findUserById($id);
        if ($user === null) {
            throw new NotFoundHttpException('The requested page does not exist');
        }

        return $user;
    }

    public function actionListkec($id){

        $kecamatans = Kecamatan::find()->where(['kota_kabupaten_id' => $id])
                                       ->orderBy('id ASC')
                                       ->all();
        // print_r($kecamatans)
				
		if (!empty($kecamatans)) {
			foreach($kecamatans as $kecamatan) {
				echo "<option value='".$kecamatan->id."'>".$kecamatan->nama."</option>";
			}
		} else {
			echo "<option>-</option>";
		}
    }

    public function actionProfile()
    {
        /** @var SettingsForm $model */
        $model = \Yii::createObject(SettingsForm::className());

backend/views/ubis/_account.php
<?php

/*
 * This file is part of the Dektrium project
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use aryelds\sweetalert\SweetAlert;

/**
 * @var yii\web\View $this
 * @var dektrium\user\models\User $user
 */
?>

<?php $this->beginContent('@backend/views/ubis/updatesf.php', ['user' => $user]) ?>

<?php $form = ActiveForm::begin([
    'layout' => 'horizontal',
    'enableAjaxValidation' => true,
    'enableClientValidation' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'wrapper' => 'col-sm-9',
        ],
    ],
]); ?>

<?= $this->render('_user', ['form' => $form, 'user' => $user]) ?>

<div class="form-group">
    <div class="col-lg-offset-3 col-lg-9">
        <?= Html::submitButton(Yii::t('user', 'Update'), ['class' => 'btn btn-block btn-success']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

<?php $this->endContent() ?>

backend/views/ubis/_user.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

/**
 * @var yii\widgets\ActiveForm $form
 * @var dektrium\user\models\User $user
 */
use common\models\Ubis;
use yii\helpers\ArrayHelper;

$ubis = ArrayHelper::map(Ubis::find()->asArray()->all(), 'id', 'nama');

?>

<?= $form->field($user, 'nik')->textInput(['maxlength' => 10]) ?>
<?= $form->field($user, 'nama')->textInput(['maxlength' => 255]) ?>
<?= $form->field($user, 'no_handphone')->textInput(['maxlength' => 255]) ?>
<?= $form->field($user, 'email')->textInput(['maxlength' => 255]) ?>

backend/views/ubis/create2.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Pelanggan */

$this->title = 'Create Pelanggan';
$this->params['breadcrumbs'][] = ['label' => 'Pelanggans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggan-create">

    <?= $this->render('_form', [
    'model' => $model,
    ]) ?>

</div>

backend/views/ubis/daftarsf.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Witel;
use common\models\Ubis;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Button;


/* @var $this yii\web\View */
/* @var $searchModel backend\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Daftar Sales Force';
$this->params['breadcrumbs'][] = $this->title;

$ubis_id = Yii::$app->user->identity->ubis_id;
$witel_id = Yii::$app->user->identity->witel_id;
$witel = Witel::find()->where(['id'=>$witel_id])->one();
$ubis_nama = Ubis::find()->where(['id'=>$ubis_id])->one()->nama;

$check = ArrayHelper::map(Ubis::listUbis(Yii::$app->user->identity->witel_id), 'id', 'nama');
$array = [0 => 'NOT SET'];
$ubis = $check+$array;


?>
<div class="user-index box box-primary">
    <div class="box-header with-border">
    <div class="pull-left">
    <?=  Button::widget([
        'label' => 'WITEL : '. $witel->nama,
        'options' => ['class' => 'btn btn-success']]);?>
    <?=  Button::widget([
        'label' => 'UBIS : '. $ubis_nama,
        'options' => ['class' => 'btn btn-primary']]);?>
    </div>
    <!-- <div class="pull-right">
        <?= Html::a('Tambah SF', ['tambahsf'], ['class' => 'btn btn-primary']) ?>
    </div> -->
    
    
    </div>



    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                // [
                //     'label' => 'Nama Witel',
                //     'attribute' => 'witel',
                //     'filter' => ArrayHelper::map(Witel::find()->asArray()->all(), 'id', 'nama'),
                //     'value'=> 'witel.nama', //relation name with their attribute
                // ],
                // [
                //     'label' => 'Kode UBIS',
                //     'attribute' => 'ubis_id',
                //     'value'=> 'ubis.kode_ubis', //relation name with their attribute
                // ],
                'nik',
                'nama',
				'no_handphone',
                'email:email',
                // 'order',                 
                // 'password_hash',
                // 'auth_key',
                // 'confirmed_at',
                // 'unconfirmed_email:email',
                // 'blocked_at',
                // 'registration_ip',
                // 'created_at',
                // 'updated_at',
                // 'last_login_at',
                // 'avatar',
                [
                    'label' => 'Lenght of Stay',
                    'attribute' => 'active_at',
                    'format'=> 'raw',
                    'filter' => array('0' =>'>6 BULAN','1'=>'>1 TAHUN'),
                    'value' => function ($model) {
                        return Yii::$app->formatter->format($model->active_at, 'relativeTime');
                    }
                ],
                [
                    'label' => 'Status',
                    'attribute' => 'status',
                    'format' => 'raw',
                    'filter' => array('0' =>'INACTIVE','1'=>'ACTIVE','99'=>'NEED APPROVAL','98'=>'REFUSED'),
                    'value'=> function ($model) {
                        if($model->status == 1) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-success btn-block',
                                ]);
                        } elseif ($model->status == 0) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-danger btn-block',
                                ]);
                        } elseif ($model->status == 99) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-primary btn-block',
                                ]);
                        }
                        elseif ($model->status == 98) {
                            return Html::tag('p', $model->statusText,[
                                'class' => 'btn btn-xs btn-warning btn-block',
                                ]);
                        }
                      }, 
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{updatesf}',
                    'buttons' => [
                        'updatesf' => function ($url,$model,$key) {
                                return Html::a('<span class="glyphicon glyphicon-edit"></span>', $url, ['class'=>'btn btn-xs btn-warning']);
                        },
                    ],
                ],

            ],
        ]); ?>
    </div>
</div>

backend/views/ubis/home.php
<?php

/* @var $this yii\web\View */

use common\models\Pelanggan;
use common\models\User;
use yii\helpers\Html;

$this->title = 'Dashboard';

$subQuery = User::find()->select('id')->where(['ubis_id'=> Yii::$app->user->identity->ubis_id])
->andWhere(['>','id',200]);

?>
      <!-- Small boxes (Stat box) -->
<div class="row">
<div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery])
                                ->count();              
        ?>
        </h3>
        <h4>Jumlah Hit</h4>
      </div>
      <div class="icon">
        <i class="fa fa-chevron-circle-up"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>1], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-yellow">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery,
                                         'status_id'=>101])->count();              
        ?>              
        </h3>
        <h4>Belum Lapor Follow Up</h4>
      </div>
      <div class="icon">
        <i class="fa fa-question-circle"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>2], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-orange">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery,
                                         'hasil_id'=>201])->count();
                           
        ?>    
        </h3>
        <h4>Belum Lapor Hasil</h4>
      </div>
      <div class="icon">
        <i class="fa fa-question-circle"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>3], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>
    </div>
  </div>

  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner text-center">
        <h3>
        <?php
          echo Pelanggan::find()->where(['salesforce_id'=>$subQuery,
                                         'hasil_id'=>203])->count();                
        ?>    
        </h3>
        <h4>Belum Deal</h4>
      </div>
      <div class="icon">
        <i class="fa fa-times-circle"></i>
      </div>
      <?= Html::a('More info <i class="fa fa-arrow-circle-right"></i>', ['dashboard','id'=>4], 
                                    ['class'=>'small-box-footer'],
                                    ); ?>    </div>
  </div>
  <!-- ./col -->
</div>

      

backend/views/ubis/ubiskec.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Witel;
use common\models\Ubis;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UbisKecamatanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Index UBIS-Kecamatan';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ubis-kecamatan-index box box-primary">
    <div class="box-header with-border">
    </div>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                [
                    'label' => 'Nama Witel',
                    'attribute' => 'witel',
                    'filter' => ArrayHelper::map(Witel::find()->asArray()->all(), 'id', 'nama'),
                    'value'=> 'witel.nama', //relation name with their attribute
                ], 
                [
                    'label' => 'Nama UBIS',
                    'attribute' => 'ubis',
                    'filter' => ArrayHelper::map(Ubis::listUbis($searchModel->witel), 'id', 'nama'),
                    'value'=> 'ubis.nama', //relation name with their attribute
                ], 
                [
                    'label' => 'Kode UBIS',
                    'attribute' => 'ubis_id',
                    'value'=> 'ubis.kode_ubis', //relation name with their attribute
                ], 
                [
                    'label' => 'Kecamatan',
                    'attribute' => 'kecamatan_id',
                    'value'=> 'kecamatan.nama', //relation name with their attribute
                ], 
                
                
                

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
</div>

backend/views/ubis/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Pelanggan */

$this->title = 'Update Pelanggan: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pelanggans', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pelanggan-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/ubis/updatesf.php
<?php

/*
 * This file is part of the Dektrium project.
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\Nav;
use yii\bootstrap\Alert;
use yii\helpers\Html;

/**
 * @var \yii\web\View $this
 * @var \dektrium\user\models\User $user
 * @var string $content
 */

$this->title = Yii::t('user', 'Perbarui Data Salesforce');


?>
<div class="pelanggan-index box box-primary">
    <div class="box-header with-border">

    


<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
        <div class="box-body box-profile">
            <?= Html::img('@web/uploads/avatar/'.$user->avatar, 
                ['alt' => 'avatar','class'=>'profile-user-img img-responsive',
                'style'=> 'width:400px']) 
            ?>

            <h3 class="profile-username text-center"><?= $user->nama ?></h3>
            
            <p class="text-muted text-center"></p>

            </div>
            <div class="panel-body">
            <?= Nav::widget([
                    'options' => [
                        'class' => 'nav-pills nav-stacked',
                    ],
                    'items' => [
        
                        [
                            'label' => Yii::t('user', 'Approve'),
                            'url' => ['/ubis/approve', 'id' => $user->id],
                            'visible' => $user->isNeedApprove,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Refuse'),
                            'url' => ['/ubis/refuse', 'id' => $user->id],
                            'visible' => $user->isNeedApprove,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Confirm'),
                            'url' => ['/user/admin/confirm', 'id' => $user->id],
                            'visible' => !$user->isConfirmed,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Block'),
                            'url' => ['/user/admin/block', 'id' => $user->id],
                            'visible' => !$user->isBlocked,
                            'linkOptions' => [
                                'class' => 'text-danger',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to block this user?'),
                            ],
                        ],
                        [
                            'label' => Yii::t('user', 'Unblock'),
                            'url' => ['/user/admin/block', 'id' => $user->id],
                            'visible' => $user->isBlocked,
                            'linkOptions' => [
                                'class' => 'text-success',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('user', 'Are you sure you want to unblock this user?'),
                            ],
                        ],
                        [
                            'label' => 'Reset Password',
                            'url' => ['/ubis/reset-password', 'id' => $user->id],
                            'linkOptions' => [
                                'class' => 'text-danger',
                                'data-method' => 'post',
                                'data-confirm' => 'Reset password menjadi 123456?',
                            ],
                        ],
                        [
                            'label' => 'Hapus Akun',
                            'url' => ['/user/admin/delete', 'id' => $user->id],
                            'linkOptions' => [
                                'class' => 'text-danger',
                                'data-method' => 'post',
                                'data-confirm' => 'Apakah kamu yakin akan menghapus akun ini?',
                            ],
                        ],
                    ],
                ]) ?>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <?= $content ?>
            </div>
        </div>
    </div>
</div>
</div>
</div>